services:
  - type: web
    name: crop-recommendation
    runtime: python310
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
